# author: saoge2222 
# Tmux configuration file

# Plugins
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'

# Color settings
set -g  default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Prefix key
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Config quick refresh
unbind r
bind r source-file "~/.tmux.conf"

# Split pane
unbind %
unbind \"
bind v split-window -v -c "#{pane_current_path}"
bind s split-window -h -c "#{pane_current_path}"

# General configuration
set -g base-index       1
set -g mouse            on
set -g mode-keys        vi
set -g renumber-windows on
set -g set-clipboard    on

# Colorscheme - gruvbox
masala="#504945"
mine_shaft="#282828"
sea_nymph="#83A598"
sapling="#\DBCCA7"

# Colorscheme - tokyonight
# Colorscheme - catppuccin

# Status line settings 
set -g status-style                 "bg=${mine_shaft},fg=default"
set -g status                       on
set -g status-position              top 
set -g status-interval              1
set -g status-left                  " #[fg=${sea_nymph},bold] #S "
set -g status-right                 "%H:%M %b-%d "
set -g window-status-current-format "#[fg=${sapling},bold] ◈ #[underscore]#I:#W"
set -g window-status-format         "#[fg=default,unbold] #I:#W"
set -g message-style                "bg=${masala},fg=${sapling}"
set -g mode-style                   "bg=${masala},fg=${sapling}"
set -g pane-border-style            "fg=${mine_shaft}"
set -g pane-active-border-style     "fg=${masala}"
